language: cpp

matrix:
  include:
    - os: linux
      env: BADGE=linux
      install:
        - pyenv install 3.6.0
        - pip install Cython
      script:
        - CC=gcc-7 && CXX=g++-7
        - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON .. && make
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - os: osx
      env: BADGE=osx
      install:
        - pyenv install 3.6.0
        - pip3 install Cython
      script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON .. && make
    - os: windows
      env: BADGE=windows
      script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" .. && cmake --build .
