add_executable(daq_thlscan_datadriven daq_thlscan_datadriven.c)
target_link_libraries(daq_thlscan_datadriven PRIVATE katherine)

add_executable(daq_thlscan_datadriven_exclude800 daq_thlscan_datadriven_exclude800.c)
target_link_libraries(daq_thlscan_datadriven_exclude800 PRIVATE katherine)

add_executable(daq_thlscan_frame_exclude800 daq_thlscan_frame_exclude800.c)
target_link_libraries(daq_thlscan_frame_exclude800 PRIVATE katherine)


